version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: blackwomanhistory
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - shared_network

  backend:
    build: .
    environment:
      FLASK_ENV: development
      DATABASE_URL: postgresql://postgres:postgres@db:5432/blackwomanhistory
    ports:
      - "9000:9000"
    depends_on:
      - db
    networks:
      - shared_network

networks:
  shared_network:
    external: true
